package com.motionstudio.part2
import kotlin.math.*
data class Point2(val x:Float,val y:Float)
sealed interface MaskShape { data class Rect(val l:Float,val t:Float,val r:Float,val b:Float):MaskShape;data class Ellipse(val cx:Float,val cy:Float,val rx:Float,val ry:Float):MaskShape;data class Polygon(val points:List<Point2>):MaskShape;data class Bezier(val points:List<Point2>):MaskShape }
data class Mask(val shape:MaskShape,val feather:Float=0f,val expansion:Float=0f,val inverted:Boolean=false,val opacity:Float=1f)
data class AnimatedMask(val keyframes:List<Pair<Double,Mask>>){init{require(keyframes.isNotEmpty());require(keyframes.zipWithNext().all{it.first.first<it.second.first})};fun evaluate(time:Double):Mask{if(time<=keyframes.first().first)return keyframes.first().second;if(time>=keyframes.last().first)return keyframes.last().second;val i=keyframes.indexOfLast{it.first<=time};return keyframes[i].second}}
object MaskRenderer { fun alpha(width:Int,height:Int,masks:List<Mask>):FloatArray{require(width>0&&height>0);val out=FloatArray(width*height);for(y in 0 until height)for(x in 0 until width){var a=if(masks.isEmpty())1f else 0f;for(m in masks){val d=distance(m.shape,x+.5f,y+.5f)-m.expansion;val edge=m.feather.coerceAtLeast(.001f);var q=(.5f-d/edge).coerceIn(0f,1f);if(m.inverted)q=1-q;q*=m.opacity.coerceIn(0f,1f);a=if(masks.size==1)q else max(a,q)};out[y*width+x]=a};return out}
 private fun distance(s:MaskShape,x:Float,y:Float):Float=when(s){is MaskShape.Rect->max(max(s.l-x,0f),max(x-s.r,0f))+max(max(s.t-y,0f),max(y-s.b,0f));is MaskShape.Ellipse->(sqrt(((x-s.cx)/s.rx).pow(2)+((y-s.cy)/s.ry).pow(2))-1f)*min(s.rx,s.ry);is MaskShape.Polygon->if(inside(s.points,x,y))-1f else 1f;is MaskShape.Bezier->s.points.zipWithNext().minOfOrNull{segDist(it.first,it.second,x,y)}?:1f}
 private fun inside(p:List<Point2>,x:Float,y:Float):Boolean{var c=false;var j=p.lastIndex;for(i in p.indices){if((p[i].y>y)!=(p[j].y>y)&&x<(p[j].x-p[i].x)*(y-p[i].y)/(p[j].y-p[i].y)+p[i].x)c=!c;j=i};return c}
 private fun segDist(a:Point2,b:Point2,x:Float,y:Float):Float{val dx=b.x-a.x;val dy=b.y-a.y;val q=((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy).coerceAtLeast(1e-8f);val t=q.coerceIn(0f,1f);return hypot(x-(a.x+t*dx),y-(a.y+t*dy))}}
