package com.motionstudio.part3
import kotlin.math.*
class ExpressionEngine{private lateinit var src:String;private var p=0;private val vars=mutableMapOf<String,Double>();fun evaluate(expression:String,time:Double,frame:Long,variables:Map<String,Double> = emptyMap(),seed:Long=0L):Double{src=expression;p=0;vars.clear();vars.putAll(variables);vars["time"]=time;vars["frame"]=frame.toDouble();vars["seed"]=seed.toDouble();val v=parseExpr();skip();require(p==src.length){"Unexpected token at $p"};return v.finite()}
 private fun parseExpr():Double{var v=parseTerm();while(true){skip();if(match('+'))v+=parseTerm() else if(match('-'))v-=parseTerm() else return v}}
 private fun parseTerm():Double{var v=parsePow();while(true){skip();if(match('*'))v*=parsePow() else if(match('/')){val d=parsePow();require(abs(d)>1e-12);v/=d}else return v}}
 private fun parsePow():Double{var v=parseUnary();skip();if(match('^'))v=v.pow(parsePow());return v}
 private fun parseUnary():Double{skip();if(match('+'))return parseUnary();if(match('-'))return -parseUnary();return parsePrimary()}
 private fun parsePrimary():Double{skip();if(match('(')){val v=parseExpr();require(match(')'));return v};if(p<src.length&&src[p].isDigit()||p<src.length&&src[p]=='.'){val s=p;while(p<src.length&&(src[p].isDigit()||src[p]=='.'||src[p]=='e'||src[p]=='E'||src[p]=='+'||src[p]=='-')&& (p==s||src[p-1] !in "+-"||src[p-1]=='e'||src[p-1]=='E'))p++;return src.substring(s,p).toDouble()};val s=p;while(p<src.length&&(src[p].isLetterOrDigit()||src[p]=='_'))p++;require(p>s);val n=src.substring(s,p);skip();if(match('(')){val a=mutableListOf<Double>();skip();if(!peek(')')){do{a+=parseExpr();skip()}while(match(','))};require(match(')'));return fn(n,a)};return vars[n]?:error("Unknown variable $n")}
 private fun fn(n:String,a:List<Double>)=when(n){"sin"->kotlin.math.sin(a.one());"cos"->cos(a.one());"tan"->tan(a.one());"abs"->abs(a.one());"min"->a.requireN(2).minOrNull()!!;"max"->a.requireN(2).maxOrNull()!!;"clamp"->{a.requireN(3);a[0].coerceIn(a[1],a[2])};"lerp"->{a.requireN(3);a[0]+(a[1]-a[0])*a[2]};"smoothstep"->{a.requireN(3);val u=((a[2]-a[0])/(a[1]-a[0]).coerceAtLeast(1e-12)).coerceIn(0.0,1.0);u*u*(3-2*u)};"random"->{val x=sin((vars["seed"]!!+a.one()*12.9898)*43758.5453);x-floor(x)};else->error("Unsupported function $n")}
 private fun List<Double>.one()=also{require(size==1)}[0];private fun List<Double>.requireN(n:Int)=also{require(size==n)};private fun Double.finite()=also{require(isFinite())};private fun skip(){while(p<src.length&&src[p].isWhitespace())p++};private fun match(c:Char)=if(p<src.length&&src[p]==c){p++;true}else false;private fun peek(c:Char)=p<src.length&&src[p]==c}
